spring:
  application:
    name: photo-map-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/photo_map
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

app:
  jwt:
    secret: 123456789
    subject: photo-map-backend
    issuer: Soneech
    ttl: 3600

server:
  port: 8080

cloud:
  aws:
    s3:
      baseUrl: https://storage.yandexcloud.net/
      secretKeyId: ${SECRET_KEY_ID}
      secretKey: ${SECRET_KEY}
      region: ru-central1
      buckets:
        photo:
          name: map-photos
        video:
          name: map-videos
